name: 229Final
channels:
  - pytorch
  - defaults
dependencies:
  - numpy
  - pip
  - pip:
    - nibabel
  - pytorch
  - torchvision
  - matplotlib
  - python=3.9
  - scipy
  - pillow
  - jupyter
  - ipykernel
  - scikit-learn
  - pandas
  - tensorflow
  - keras

